package com.user_service.enums;

public enum ExceptionStatus {

    USER_NOT_FOUND("USER_NOT_FOUND"),
    EMAIL_IS_ALREADY_ACTIVATED("EMAIL_IS_ALREADY_ACTIVATED"),
    EMAIL_IS_ALREADY_EXIST("EMAIL_IS_ALREADY_EXIST"),
    USERNAME_IS_ALREADY_EXIST("USERNAME_IS_ALREADY_EXIST"),
    USER_EMAIL_CONFIRMATION_NOT_FOUND("USER_EMAIL_CONFIRMATION_NOT_FOUND"),
    USER_EMAIL_CONFIRMATION_TOKEN_EXPIRED("USER_EMAIL_CONFIRMATION_TOKEN_EXPIRED");


    private String name;

    ExceptionStatus(String name) {
        this.name = name;
    }
}
