server:
  port: 8080

spring:
  application:
    name: ${APPLICATION_NAME:user-service}

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/user_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

grpc:
  server:
    security:
      enabled: false
    port: 9090
    netty:
      keep-alive-time: 60s
      keep-alive-timeout: 20s

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
  level:
    root: info

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      grpc.port: ${spring.grpc.server.port}
  client:
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_HOST_URL:http://localhost:8761/eureka/}

email-confirmation:
  token:
    expiration-durability: 6